### ISSUE TITLE
Minimal UI option

### ISSUE THREAD

**Issue by rasenplanscher** [threema-ch/threema-web#1009]
I'd like to use ThreemaWeb in Rambox, and the header, footer, and padding are taking up too much space. Please use a focussed design, at least for small viewports. WhatsApp Web does that well: There's only the list of contacts and the message area.

I don't need a header telling me this is Threema, I know that, so it can just go. Also, I frankly don't care about the footer items 99% of the time, so they can be safely hidden in the **⋮**-menu.

**Comment by dbrgn** [comment]
Please note that Threema Web is in [maintenance mode](https://github.com/threema-ch/threema-web/pull/996) so no new features will be added.

(If a PR comes in with a change that's very simple and is unlikely to introduce any new bugs, it will be considered for merging though!)

**Comment by jwanner83** [comment]
I'm interested in implementing this feature. Is it okay if I give it a shot? :)

**Comment by jwanner83** [comment]
I thought it would make sense to have a new setting called "User Interface / Benutzeroberfläche" where you can change from "default" to "minimal". This setting is then stored in the localStorage.

### Setting
<img width="830" alt="Bildschirmfoto 2021-01-28 um 10 40 18" src="https://user-images.githubusercontent.com/38656104/106119220-3a1c9c00-6155-11eb-9f3d-506a62a45bd1.png">

It then adds a class to the body which makes it possible to style certain elements the way we want (like to remove the header / footer ...)

### Default User Interface:
<img width="1473" alt="grafik" src="https://user-images.githubusercontent.com/38656104/106120261-743a6d80-6156-11eb-99d0-c5a05bb36c14.png">

### Minimal User Interface:
<img width="1475" alt="grafik" src="https://user-images.githubusercontent.com/38656104/106120288-7e5c6c00-6156-11eb-9ea8-bd1dc34132a3.png">

To still be able to see the version of the application, I added a button which opens a version dialog. This button is only visible if the minimal theme is active.

#### Button
<img width="265" alt="Bildschirmfoto 2021-01-28 um 10 51 00" src="https://user-images.githubusercontent.com/38656104/106120488-b95e9f80-6156-11eb-9ef6-b2ac70e8b716.png">

#### Dialog
<img width="528" alt="Bildschirmfoto 2021-01-28 um 10 51 28" src="https://user-images.githubusercontent.com/38656104/106120539-c8dde880-6156-11eb-9faa-05c6b7a2c353.png">


But I have a question about the translations. I've added the new ones only in German. Do I have to add them as well in all the other languages?

And another question: is the way I did it valid? Or is too dangerous to introduce new bugs? If yes, it's not that big of a deal, I didn't spend as much time on this, and I've found it quite fun to do :)

**Comment by samuelT2** [comment]
Hi Jonas - I also stumpled accross some interesting tasks here, though, the team around Threema seems (understandably) pretty busy since all kind of messengers are overrun because WhatsApp changes it's privacy policy. Your changes look great, however, to make the life of the moderators as easy as possible, have a look at the [contributing guidelines](https://github.com/threema-ch/threema-web/blob/d555d40b80bc339f8ad155cfbbad6a2c3e595a95/CONTRIBUTING.md). If you want to propose changes, fork the project, create a pull request and sign the CLA. Also make sure to follow the formatting standards by running the lint tests (and of course the unit tests).

**Comment by samuelT2** [comment]
Additionally, if you want to take up some low hanging fruits which have a chance that they get accepted (because Threema Web is in [maintenance mode](https://github.com/threema-ch/threema-web/pull/996)), have a look at [this filter](https://github.com/threema-ch/threema-web/labels/good%20first%20issue).

**Comment by dbrgn** [comment]
Thanks @samuelT2!

@jwanner83 your general approach looks good! I haven't looked at the code though. Please send a PR as soon as it's ready for review.

Regarding the translations: Just add English strings (and update German translations if you want to), the rest will be done via Transifex (see https://github.com/threema-ch/threema-web/blob/master/TRANSLATING.md). We regularly update translation strings before creating a release.

**Comment by jwanner83** [comment]
@dbrgn Thanks for the informations. I've added the english and german translations :) 
The pull request is now open. But no stress :)
