### ISSUE TITLE
Allow more then one group admin

### ISSUE THREAD

**Issue by samuelT2** [threema-ch/threema-web#1030]
Similar to other messengers, it would be great if the group creator could "promote" other members to admin, allowing adding or removing other members etc.

Target: iOS app

**Comment by dbrgn** [comment]
Since this is a general Threema feature request, and not about Threema Web, I'm going to close this. Please direct feature requests at the Threema support (https://threema.id/*SUPPORT)!

As a sidenote: For privacy reasons, in contrast to other messengers, Threema stores group information on the devices only. This means that in case of conflicting information, there is no way to resolve that if there's no clear authority. Imagine that you add a second admin to a group. Then you remove that admin again, but at the same time the other admin removes you from the group. Since the two messages are sent in parallel, some members will now have a group with you as admin, and others will have a group with the other admin, depending on which message "wins" the race. You need some kind of authority to resolve this conflict. Distributed consensus is a hard academic problem.

Right now, with a single admin, conflicting group state can be resolved by re-syncing the group. The group ID actually contains the group admin's ID, so on a protocol level, the group and the admin are inherently linked.

(Note: We do have some ideas how the group management can be improved without true multi-admin groups. We cannot comment on those at this stage though.)
