### ISSUE TITLE
Allow search in Messages tab

### ISSUE THREAD

**Issue by samuelT2** [threema-ch/threema-web#1031]
Allow search through chat names and chats content by pulling down Messages, showing a search bar (similar to what is already there in Groups).

Target: iOS app

**Comment by dbrgn** [comment]
Is this feature request about Threema Web? If not, please send your feature request to the Threema support https://threema.id/*SUPPORT.

If this is about Threema Web: There's already a chat search. There will not be full content search, because that would require updates to both the protocol and the app support code, and Threema Web is currently in maintenance mode (see top of README).
