### ISSUE TITLE
Color getting messed up sending pictures

### ISSUE THREAD

**Issue by ozzi-** [threema-ch/threema-web#1045]
## Bug Description

When sending images on Threema Web, the colors get messed up (as in loose "vibrancy")

## Steps to Reproduce (for bugs)

1. Create PNG and fill it with grey (127,127,12)
2. Send it via Threema Web
3. Download it again
4. The color is now (124,124,124)

Sending said saved image and sending it again, will result in 121,121,121
The same behavior can be seen on JPGs, where the degradation isn't as deterministic though.

## Your Environment

* Threema Web version: 2.3.11 Säntis
* Threema App version: 4.5.1 B 669 - Threema Shop
* Browser name and version: Firefox 86.0.1
* Computer operating system and version: Win 10 - 2004
* Smartphone operating system and version: Xiaomi A3, Android 11

**Comment by ozzi-** [comment]
![before](https://user-images.githubusercontent.com/7944573/111588569-06103f80-87c4-11eb-8375-7aa1cbd0a1a6.png)
![after](https://user-images.githubusercontent.com/7944573/111588810-538cac80-87c4-11eb-9dea-8ff9cb453f7c.png)

**Comment by threema-danilo** [comment]
The reason is that the Threema protocols always sends image messages as JPEG. This is a choice that works very well for photos, but unfortunately not for PNGs. You are seeing the results of its compression.

To avoid this, send thte image as file by checking the "send as file" checkbox. In that cases, the image will not be re-encoded and will be sent as-is.

**Comment by ozzi-** [comment]
oh that explains a lot, thanks for the tip with "send as file"
