### ISSUE TITLE
Threema-Desktop blurry icon

### ISSUE THREAD

**Issue by amithiel** [threema-ch/threema-web#1097]
## Bug Description
The icon in the dock is blurry.

Describe the problem.
This happens only in Gnome desktop, as far as i know. If anyone can tell me where the icon is store, i can try to replace it myself.

Tried to edit the icon in ( /usr/share/applications/threema-desktop ) , but that doesn't change the icon presented in the dock.

[screenshot](https://i.imgur.com/C97ksJ2.png)

## Your Environment

ArchLinux - Gnome 41.1

* Threema Web version:
* Threema App version: 2.3.17 (1.0.3)
* Browser name and version:
* Computer operating system and version:
* Smartphone operating system and version:

**Comment by threema-danilo** [comment]
Hi, please report issues with Threema Desktop to the Threema support (help@threema.ch or https://threema.id/*SUPPORT) or open a thread in the German Threema-Forum (https://threema-forum.de/).

The issue with the blurry icon is a known issue that will be fixed in a future version. The icon should be at `/usr/share/pixmaps/threema-desktop.png` on your file system.
