### ISSUE TITLE
App does not start/install anymore (on W7) - says instead "GetpackageFamilyName()" in "KERNEL32.dll" couldn't be found

### ISSUE THREAD

**Issue by itsbrody** [threema-ch/threema-web#1172]
## Bug Description

Because of a longer time not having used THREEMA Web App (on my Windows 7), I've been acknowledged on last start to update the APP. Downloading "latest" worked, but while starting (for installation) its some time busy (for preparing) and then showing the attached popup.

## Steps to Reproduce (for bugs)

1. Start downloaded exe file
2. see "Installing" Popup
3. see "Error Popup"
![kernel32GetPackageFamilyName](https://user-images.githubusercontent.com/19346144/229304804-047742cc-735a-4f40-8e4d-bc81d36931ee.png)

## Your Environment

* Computer operating system and version:
Windwow 7 Professional 
6.1.7601 SP1 Build 7601

**Comment by threema-lenny** [comment]
Windows 7, 8 and 8.1 are EOL and no longer supported by Electron since Electron version 23.0.0 which is required to run Threema Desktop.

But you can still use the web variant on https://web.threema.ch/ or use an older version of Threema Desktop (not recommended). In any case, keep in mind that Windows 7/8/8.1 are EOL and won't receive security updates, so they should no longer be used for a secure messenger.
