### ISSUE TITLE
Cannot pair when phone is on the same LAN as the browser

### ISSUE THREAD

**Issue by agross** [threema-ch/threema-web#12]
Hi,

just started testing Threema web. I cannot pair my phone with web.threema.ch while my phone is connected to the same LAN as my web browser (on a PC). While both devices are on the same network, after scanning the QR code a spinner will be added to the session list and spin forever. When the phone is on mobile data, pairing succeeds.

After pairing succeeded, when the phone gets reconnected to the LAN Threema Web detects that the connection is broken and closes the session. After returning the phone to mobile data the session is resurrected in the web browser.

FYI, I'm running a IPv4/IPv6 dual stack configuration with an IPv6 firewall in place. Android 6.

Please let me know whether you need more information. The Threema log file does not contain additional information beyond the messages I received while pairing was attempted.

**Comment by dbrgn** [comment]
Could you test whether other WebRTC based projects work with the same two devices connected to the same network, e.g. https://appear.in/?

**Comment by agross** [comment]
@dbrgn appear.in works: same workstations as with Threema, same phone, same LAN for both devices.

**Comment by dbrgn** [comment]
Can you look at the debug console of your browser (F12)? Does it contain anything interesting? Maybe share a gist to the relevant looking section?

**Comment by lgrahl** [comment]
Posting the log of the browser would probably be helpful.

Also, using wireshark on the PC to capture `stun` packets (can be used as a display filter) would help to see if ICE is working between the devices (turn off other WebRTC applications before though).

**Comment by agross** [comment]
https://www.dropbox.com/sh/t1sfk9nij7sw1x2/AACUPJABO-3n8HHL7Dt3Hr0za?dl=0

Contains WireShark captur and the console log.

**Comment by lgrahl** [comment]
Have you tried using Firefox?

**Comment by dbrgn** [comment]
What I see is that the ICE connection between the devices is lost about a minute after the connection buildup succeeded. If you switch networks, it's normal that the connection is lost. Otherwise we'd need to keep a permanent websocket signaling connection open. This is something that we wanted to avoid to keep the amount of metadata on the server minimal.

On connection loss the webclient tries to auto-reconnect, which fails. This is a known issue, sometimes reconnecting is a big buggy. This will hopefully be fixed in the next release.

The other thing you mentioned is that connecting never succeeds if both devices are in the same network. @agross, was your phone initially in mobile network when you created that log? If yes, could you send another browser log trace with a failed connecting attempt?

**Comment by agross** [comment]
@dbrgn The issue is that I cannot pair when both devices are on the same LAN. Pairing only succeeds on mobile data. Once paired, I need to be on mobile data to restore a once-paired session. So yes, in order to create the logs I needed to make the switch from mobile data to wifi.

**Comment by agross** [comment]
@lgrahl FF shows the same behavior as Chrome.

**Comment by dbrgn** [comment]
@agross But you can reload the browser, open the debug console (F12), attempt to pair and then copy the debug log after pairing fails.

**Comment by agross** [comment]
I'm on the run right now. I'll send you a capture of a failed pairing attempt later today. The only visible indication of pairing is currently that the phone shows a spinner. No message in the browser UI.

**Comment by lgrahl** [comment]
I don't even see an attempt in the Wireshark tracefile for direct device-to-device communication. It's always TURN-relayed.
Can you provide another Wireshark tracefile for FF and a log? Please also mention what kind of action you take at what point in time.

**Comment by dbrgn** [comment]
> The only visible indication of pairing is currently that the phone shows a spinner.

If the browser does not react to the connection attempt, that would indicate that the connection from your phone to the signaling server fails already.

You could enable the debug log in the app (Threema > Settings > Troubleshooting > "Log to File"), try to connect again and then send us the logfile (/sdcard/Threema/message_log.txt, doesn't contain any unencrypted or otherwise readable message contents). If you don't want to post it in public, you can also open a support ticket (https://threema.ch/en/support) and reference this comment.

**Comment by Anke** [comment]
I cannot pair either in WiFi nor in mobile mode. Firefox stops at 99%.

I have Android 4.3 on Galaxy S3 with Bitdefender Mobile Security on board, and I temporarily deactivated browsing security. PC with Win10Pro, Firefox and Chrome (latest builds) and F-Secure (deactivation didn't change anything.

I'm not such an expert, but I'l attach my Threema and Firefox console log files:

[message_log.txt](https://github.com/threema-ch/threema-web/files/777665/message_log.txt)
[firefox_threemaweb_log.txt](https://github.com/threema-ch/threema-web/files/777672/firefox_threemaweb_log.txt)

**Comment by dbrgn** [comment]
@Anke thanks. Your issue is different than the one by the original poster, it appears that you stumbled upon a bug on the app side. We will look into it.

**Comment by agross** [comment]
Alright, I think I found the culprit. It was due to broken IPv6 connectivity by my ISP.

Normally, the dual stack configuration works, but today the v6 part got broken. By the time I tried pairing the phone it had an IPv6 address which it used to create outgoing connections (that never reached their destination). With mobile data on the other hand the phone only had IPv4 available, so outgoing connections from the phone worked.

**Comment by dbrgn** [comment]
@agross good that you could solve it! local LANs are the easiest case for WebRTC, therefore I was a bit confused why it wouldn't work :)

**Comment by agross** [comment]
@dbrgn Thanks for your quick response! I find it exceptional that you decided to open-source Threema Web and accept support requests like this on GitHub! 👍

**Comment by dbrgn** [comment]
@Anke please follow #38 regarding the 99% bug.
