### ISSUE TITLE
Latest update not released, getting annoyed by update pop-up

### ISSUE THREAD

**Issue by herpaderpaldent** [threema-ch/threema-web#1206]
This is a draft, waiting for the annoying alert to appear again

## Bug Description

- an annoying pop up always claims that a new update is available. 
- upon installing via ui OR installing the latest version from the threema homepage, the update info persists

it seems the latest version from early march has not been compiled as version for macOS

## Steps to Reproduce (for bugs)

1. Have Threema Web App on Mac installed
<img width="519" alt="grafik" src="https://github.com/threema-ch/threema-web/assets/6583519/b11f9690-b932-4ef9-b147-2bd68e1f4702">

3. Use Threema Web App
4. Get random update available prompt
<img width="318" alt="grafik" src="https://github.com/threema-ch/threema-web/assets/6583519/ee1dee9f-2a20-49a6-af39-f63f24d7bf61">
5. Restart as prompted

7. Have the same version ....
<img width="524" alt="grafik" src="https://github.com/threema-ch/threema-web/assets/6583519/3f48569d-c96c-4eb3-80c9-5ee57ee5f7af">

8. download latest from homepage
<img width="532" alt="grafik" src="https://github.com/threema-ch/threema-web/assets/6583519/670da3ee-3335-403d-892b-90480e1d0fa2">

## Potential Solution

actually release 2.5.4 as download on your homepage

## Your Environment

* Threema Web version:
* Threema App version:
* Browser name and version:
* Computer operating system and version:
* Smartphone operating system and version:

**Comment by threema-danilo** [comment]
This affects Threema Desktop and not Threema Web, but thanks for the note, we'll take a look.

**Comment by herpaderpaldent** [comment]
Thank you @threema-danilo the version pop up lead me to this repository. I am sorry. Shall i recreate it on the other repo? 
<img width="544" alt="image" src="https://github.com/threema-ch/threema-web/assets/6583519/5c86cdb6-4906-419b-aa95-15c8c09c77ad">

**Comment by threema-danilo** [comment]
@herpaderpaldent to summarize the repository structure:

- https://github.com/threema-ch/threema-web/ is the actual implementation of the Threema web client. It is used both on web.threema.ch and is embedded in Threema 1.0 for desktop.
- https://github.com/threema-ch/threema-web-electron/ is the Electron wrapper around Threema Web. This is where the update check happens.

We did not enable the issue tracker for the `threema-web-electron` repository, because we prefer if these requests are channelled through the regular support system (https://threema.ch/en/support-request). However, since this is now something that we've heard occasionally from a few people, let's keep the issue here for now.

Regarding your issue, in the two screenshots of the version, I can see that the actual upgrade did happen successfully, from 1.2.40 to 1.2.41. In both versions, the embedded version of Threema Web remains at 2.5.3 (2.5.4 will be included in the next release).

Do you still get the "update available" prompt?

**Comment by thepatcher** [comment]
I had the same issue with the pop-up, for months, but yesterday I downloaded the newest version from https://releases.threema.ch/web-electron/v1/release/Threema-Latest.dmg and now the version information says "Version 2.5.3 (1.2.41) Lütispitz" and the pop-up is gone.

**Comment by herpaderpaldent** [comment]
Hi @threema-danilo 

> Do you still get the "update available" prompt?

i can confirm just like @thepatcher, that with the latest version the prompts are gone with the 1.2.41. Somehow the upgrade via ui in contrast to downloading the .dmg did not occur.

**Comment by threema-danilo** [comment]
Thanks for the confirmation! It was probably an issue with a single release, where something went wrong in the build process. Manually updating should help.

**Comment by herpaderpaldent** [comment]
<img width="310" alt="image" src="https://github.com/user-attachments/assets/689b26c6-3139-4831-bddc-4a66ace545dc">
This is the latest pop-up appearing. 

How much longer on v2 for android and desktop? Have you resigned?

**Comment by threema-danilo** [comment]
@herpaderpaldent thanks for letting us know. We recently did an update of various server certificates, and this seems related. Should get fixed soon!

**Comment by herpaderpaldent** [comment]
Thank you @threema-danilo
