### ISSUE TITLE
Groups tab

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#132]
## Expected Behavior

Add a special tabs for groups similar to the "My groups" menu on Android.
This allows you to easily find a group if you have not send a message to it for some time.

## Current Behavior

There is no such tab.

## Possible Solution

Add a tab or a menu similar to the Threema app where you also include "My backups" (see https://github.com/threema-ch/threema-web/issues/65).

*not my idea*

**Comment by IndianaDschones** [comment]
I´ll implement the groups tab in the next few days.

> where you also include "My backups"

#65 is none of my business 😉

**Comment by dbrgn** [comment]
I'm not sure yet whether we want that as a tab or not. It's mostly redundant, since all groups are accessible directly through the conversations list. What would such a tab give us that the conversation list does not?

Maybe filters in the conversation list would be a better approach? (This is a question, not a statement 🙂 )

**Comment by lgrahl** [comment]
What about groups that have empty conversations. Are they being displayed?

**Comment by dbrgn** [comment]
> What about groups that have empty conversations. Are they being displayed?

Yes. Just like in the Android app, by the way :)

**Comment by IndianaDschones** [comment]
I think you´re right, the group menu/tab/however is redundat. Do you know how other web-messenger handle this (Signal, Telegram, Whatsapp,... ?)

The Android app offers a `New Message`-Menu (click on the FAB (+) in the conversationlist and then hit `New Message`). Since the Webapp does not offer such an menu, i think we don´t need a group tab.

By the way 3 tabs look very strange, and for the sake of completeness we would need an `Distribiution Lists`-Tab, which would be too much.

**Comment by dbrgn** [comment]
I don't think others have an explicit UI for group management. But in the end it doesn't really matter what others do :)

What I could imagine as being useful is a kind of filtering interface where you can filter conversation by type (contact, group, distribution list) or age. I'm not sure how that could be integrated into the UI in a clean way though. And usually the search box is enough for filtering.

I'll close this issue for now. If someone has further feedback, feel free to comment.

**Comment by rugk** [comment]
> What I could imagine as being useful is a kind of filtering interface where you can filter conversation by type (contact, group, distribution list) or age.

I like that idea. So: https://github.com/threema-ch/threema-web/issues/283

As for implementation: Just a [filter icon](http://fontawesome.io/icon/filter/)…

**Comment by dbrgn** [comment]
> As for implementation: Just a filter icon…

Yes, but how should the dialog look? What options should there be? What types of input elements? How can the filter be reset? How do we avoid that people accidentally set a filter and then complain that they can't see some of the conversations?
