### ISSUE TITLE
1 linebreak become 3 when pasted into the text field

### ISSUE THREAD

**Issue by nurps** [threema-ch/threema-web#134]
If i copy and paste a text with a normal single line break. It looks normal in die text entry field of Threemaweb, but after sending I get 3 empty lines instead of just one. Looks terrible and ist annoying for longer texts.

**Comment by dbrgn** [comment]
I cannot reproduce this, neither in Chromium nor in Firefox.

Can you let us know what browser and OS you're using? And give us steps we can follow to reproduce this issue? (That's what the issue template is for that you deleted when creating this issue.)

**Comment by nurps** [comment]
I have a text file created with Windows10 notepad containing something like:

"Test test,

test test test test."

Copied that into Chrome Threema and it became 3 empty lines after sending, but shows with one line (correctly) in the text field before sending.

**Comment by dbrgn** [comment]
Ah. Then it must be related to Windows line endings... :roll_eyes: 

Thanks for reporting.

**Comment by IndianaDschones** [comment]
I did some investigations. Chrome handels the input different to Firefox:

This is the text with CR/LF on Windows ([inputFromWindows.txt](https://github.com/threema-ch/threema-web/files/821250/inputFromWindows.txt)):

![text-npp](https://cloud.githubusercontent.com/assets/6652142/23611556/3ae4717a-0278-11e7-908b-d25f44ee51f6.PNG)

This is the text pasted in the Chrome textfield

![text-chrome](https://cloud.githubusercontent.com/assets/6652142/23611558/3ae858d0-0278-11e7-8113-bbe40d8af661.PNG)

and in the Firefox textfield

![text-firefox](https://cloud.githubusercontent.com/assets/6652142/23611557/3ae4ac94-0278-11e7-8e26-3debb9b46045.PNG)

Hope this helps solving the issue because only Chrome adds additional linebreaks.

**My System**
Windows 8.1 64-Bit
Chrome 56.0.2924.87
Firefox 51.0.1 (64-Bit)
