### ISSUE TITLE
Audio notification for new messages

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#16]
At the moment, I only get notified about new messages when the desktop notification option is enabled.

However, it does not play any sound on my computer (Firefox 51.0.1; Ubuntu 16.04).
It would be great if Threema Web played a sound when you get a new message (and independent from desktop notification).

Of course it should be possible to enable/disable the sound notification.

**Comment by rugk** [comment]
I think this is one of the main reasons to use desktop notifications: to get a sound.

Why would you want to get a sound, but no desktop notifications?

**Comment by ovalseven8** [comment]
> Why would you want to get a sound, but no desktop notifications?

Well, people are different. I don't like notifications on the desktop that behave like pop-ups. Moreover, there is the content of the message in the notification. If a person is sitting with me on the computer (because I show him something for a short moment) he can read the messages. Without the desktop notification I just can read the messages after the person is not sitting on the computer with me anymore.

**Comment by rugk** [comment]
> I don't get any sound with push notification enabled?

Desktop/browser notifications, not push notifications. It might depend on your browser/OS whether you get a sound…

**Comment by patrick-tee** [comment]
No sound on Samsung Galaxy Tab S2 using latest version of FF and Android 6. Would be nice if this could be added. I guess, there should not be any technical issue to realize it.
BTW: The request to enable push notifications disapeared during page loading - too fast to confirm...

**Comment by dbrgn** [comment]
> BTW: The request to enable push notifications disapeared during page loading - too fast to confirm...

@patrick-tee I opened a separate issue for that: #24

> I guess, there should not be any technical issue to realize it.

Probably not, but we need a configuration dialog before being able to implement this. Audio notifications will probably be off by default, I could imagine a lot of people being annoyed by it.

**Comment by IndianaDschones** [comment]
Since the notification settings are implemented (#8) I´d like to implement the sound as well.

I´ll implement it like @ovalseven8 said

>  independent from desktop notification

This means even if the "popup" notifications are disabled you can enable sound and vice versa.

@dbrgn Should I disable sound (hiding the option) if the user denied notification permission? I mean it´s independent and does not need any permission but some users may think "I said i don´t want notifications (even if sound is off by default and they activated it) but it still plays sound"?

Also someone @threema-ch has to provide a notification sound. Maybe in `public/sounds/notification.mp3` (that´s the path I will use).

**Comment by dbrgn** [comment]
@IndianaDschones I would simply disable the sound by default and make the option independent from desktop notifications.
