### ISSUE TITLE
Security audit for Threema Web

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#173]
Compared to standalone applications it is probably harder to create a secure browser-based web application.

Even popular and heavy-used web applications are affected of those problems regularly. Because Threema wants to provide "seriously secure messaging" it would make sense to look at the code just for security vulnerabilities.

Just today it was published that they found a serious vulnerability in WhatsApp Web and Telegram Web:
http://www.zdnet.com/article/attackers-can-hijack-millions-of-whatsapp-telegram-accounts-in-seconds/

Additionally, also Threema Web has already fixed a potential security flaw with v1.0.2.

Perhaps one should wait until some more bugs are fixed and the most important desired features are implemented. But then I'd love if Threema could hire a reputable company that is specializing in web security.

I am sure that Threema puts lot of efforts in creating a secure software. Nonetheless, it's never a bad idea to have specialized people to have a look at it - especially at web applications.

**Comment by dbrgn** [comment]
Reviews are a good idea, yes. However, to put two of your statements into perspective:

> Just today it was published that they found a serious vulnerability in WhatsApp Web and Telegram Web

Agree about the Whatsapp part, however the exploit for Telegram is a bit contrived: http://telegra.ph/Checkpoint-Confusion-NEWS

> Additionally, also Threema Web has already fixed a potential security flaw with v1.0.2.

Potential, although I couldn't manage to actually execute any code (I tried). So it's well possible that it had no security implications at all.

Anyways, security reviews are valuable since humans make mistake. And until a real audit is done, we invite the community to break our code if possible. The contact details for responsible disclosure are [in the README file](https://github.com/threema-ch/threema-web#security)!

**Comment by lgrahl** [comment]
Anything left to say here? :)

**Comment by ovalseven8** [comment]
Not really, security audit for SaltyRTC and the web application would make sense. However, it's Threema's turn.

**Comment by dbrgn** [comment]
Let's close this for now. As mentioned in https://github.com/threema-ch/threema-web/issues/173#issuecomment-286856642, when an audit happens, we'll publish it of course. Until then, community audits are welcome. The contact details for responsible disclosure are [in the README file](https://github.com/threema-ch/threema-web#security).
