### ISSUE TITLE
Sharer-URL

### ISSUE THREAD

**Issue by theBear** [threema-ch/threema-web#190]
Are there any plans to implement a simple Sharer-URL for the web-client like whatsapp and other messengers already have?

`https://web.whatsapp.com/send?text=TEXTorURL` (web app)

`whatsapp://send?text=TEXTorURL` (mobile)

This snippet only works on mobile devices:

`threema://compose?text=TEXTorURL`

I'm looking forward to it. :-)

Best regards from Berlin
Sebastian

**Comment by dbrgn** [comment]
You mean in the web browser?

**Comment by theBear** [comment]
Yes, for [https://web.threema.ch](https://web.threema.ch)

**Comment by dbrgn** [comment]
The `threema://add?id=ABCDEFGH` URL is already supported. The compose action not yet.

**Comment by theBear** [comment]
You missunderstood it. As I said in the entry post: `threema://compose?text=TEXTorURL` or `threema://add?id=ABCDEFGH` works for mobile devices well, where the app is installed, but NOT for sharing in Webbrowsers like WhatsApp `https://web.whatsapp.com/send?text=TEXTorURL` and Telegram `https://telegram.me/share/url?url={url}&text={title}` already use it. Now? ;-)

**Comment by theBear** [comment]
Take a look at:

[https://github.com/bradvin/social-share-urls](https://github.com/bradvin/social-share-urls)

**Comment by dbrgn** [comment]
Ah, I see. That won't be easily supported, since every share from another page (that opens the https://web.threema.ch URL) will require a new login (we don't use cookies or similar to persist the login session across tabs). I'm not sure if that's a satisfactory solution - in that case you're faster off by simply copy-pasting the text.

There would also be an option to register a custom protocol in the browser. The problem is that Firefox only allows certain whitelisted protocol names, other protocol names must be prefixed with `web-` (so `web-threema://compose?text=TEXTorURL`). That would make it incompatible with the app, and would only work if people used Threema Web before, otherwise nothing will happen when clicking on the link. So that's not satisfactory either.

I'll add support for the compose action from within Threema Web though.

**Comment by rugk** [comment]
Instead of another login for a be link, can't the new tag just somehow signal the information to the tab already open and logged in?
Web workers or so?

**Comment by dbrgn** [comment]
I don't have experience with web workers, but I'm pretty sure that web workers cannot access other tabs' content and that other tabs cannot access the current tab's webworkers

**Comment by rugk** [comment]
I've also no idea, but if they are from the same origin, maybe they can sent messages to each other (there are also so-called "shared workers"). I think [in one spec example](https://html.spec.whatwg.org/multipage/workers.html#shared-workers-introduction) this is explicitly mentioned:
> Finally, the example is extended to show how two pages can connect to the same worker; in this case, the second page is merely in an iframe on the first page, but the same principle would apply to an entirely separate page in a separate top-level browsing context.

([online example](https://html.spec.whatwg.org/demos/workers/shared/003/test.html))

In any case there are actually [also many other ways to do so](https://stackoverflow.com/questions/28230845/communication-between-tabs-or-windows).
With the message all important things could just be sent to the tab, so that there the important stuff is done.

I also saw [a HTML5 cross-window API being mentioned](https://stackoverflow.com/questions/3203530/accessing-the-content-of-other-tabs-in-browser#3203583), but it also only seems to allow sending messages.
