### ISSUE TITLE
Wrong Emoji for heart symbol

### ISSUE THREAD

**Issue by Kurisutian** [threema-ch/threema-web#199]
## Expected Behavior
When receiving a :heart: symbol from Threema send through iOS to the webclient the heart symbol shows in the chat.

## Current Behavior
Instead of the heart symbol the policeman head symbol shows.

## Steps to Reproduce (for bugs)
1. Open Webclient
2. Have an iOS (10.3.1) User send a message with the ❤️ Symbol
3. Check the received message on the webclient

## Your Environment
* Threema Web version: 1.1.0
* Threema for Android version: 3.13
* Threema for Android source: Play Store
* Browser name and version: Chromium 57.0.2987.133 (64-bit)
* Operating system and version: Manjaro Linux 17.0 (all updates included)

**Comment by dbrgn** [comment]
Thanks for the report. We already have a ticket open for that: #54.

Unfortunately we're still waiting for the new Emoji release by http://emojione.com/. They have postponed the release date multiple times now. Once that's out, it should fix these problems, which are caused by lacking support of some newer unicode features deployed on iOS devices.
