### ISSUE TITLE
Backarrow <- gets small

### ISSUE THREAD

**Issue by PantherPaulchen** [threema-ch/threema-web#205]
## Expected Behavior
When pointing at the Backarrow <- in the conversation window with the mouse, his change of size should be the same.

## Current Behavior
When there are many group members and their names do not fit into the current window, the backarrow jumps very small to the left side, so that it is hard to hit the arrow. The size of the small arrow seams to depend on window size.

## Possible Solution
Don' know.

## Steps to Reproduce (for bugs)

1. Enter a group conversation with many members
2. move mouse to <-

## Your Environment

* Threema Web version: 1.1.0
* Threema for Android version: 3.13
* Threema for Android source: Threema Store|
* Browser name and version: tested on Firefox and Chrome
* Operating system and version: tested on Ubuntu & Windows10

**Comment by IndianaDschones** [comment]
@dbrgn Is there a reason you used an svg instad of material icon or button w/ md-icon for the back arrow? If no I would use them instead of the svgs. This solves the issue. I would replace them everywhere (when creating groups and so on) to be consistent.

Another solution would be to remove the `width: 105%` property when hovering.

**Comment by dbrgn** [comment]
@IndianaDschones replaced with md-icon!
