### ISSUE TITLE
Show warning when the battery is low

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#268]
When using WhatsApp Web and the battery is low, a warning is displayed:
![2017-07-16-213015_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28257009-c1ed7ce0-6ac7-11e7-9acc-c4e185871b62.png)

Would make sense for Threema Web too!

**Comment by ovalseven8** [comment]
@dbrgn 
I would use [this icon](https://material.io/icons/#ic_battery_alert) and color it together with the percentage value of the battery (i.e. "12%") in red/orange.
If someone hovers over it, a tooltip appears saying something like:
```
                <em>Low battery</em>
Please charge the battery to further use Threema Web.
```

Would fit to your recent PR (#265).

**Comment by dbrgn** [comment]
We already use that icon when battery percentage is below a certain value (20% I think). It's not red, but I think if we really want to warn people about the battery level we should use a warning banner thing (like the screenshot above) instead of a red icon.

**Comment by ovalseven8** [comment]
> We already use that icon when battery percentage is below a certain value (20%), see #265.

Oh, yeah. Didn't look at the code carefully enough. :smile: 

> It's not red, but I think if we really want to warn people about the battery level we should use a warning banner thing (like the screenshot above) instead of a red icon.

Okay, makes sense.

I think the warning banner in WhatsApp Web looks pretty good (they also use the same icon, right?). So Threema Web should probably just adapt it.

For consistency: It should be displayed when also the icon changes (20 % at the moment). Would not be a good idea if the icon changes at 20 % and the warning at 25 % or 15 %.

**Comment by rugk** [comment]
> Would not be a good idea if the icon changes at 20 % and the warning at 25 % or 15 %.

Why not? I think that is okay. A "small indicator" for 20% and when it get's critical display the banner. Or just display it multiple times:
* 20% – indicator change
* 15% – banner
* 5% – another banner

**Comment by ovalseven8** [comment]
Well, my thought was that the user should know WHY the icon changed and that's the case when the warning banner is showed.

**Comment by rugk** [comment]
Yeah, maybe. How is the behaviour with a "usual" Android (AOSP)? Does it only show a banner when the icon changes to `!` or does the icon change before?
Maybe we should just follow that behaviour…

**Comment by IndianaDschones** [comment]
IIRC Android shows a banner at 15% (maybe this value can be changed by the user/oem) and another one when the energy saving mode activates (at 15% or 5% or never, at least this are AOSP options).

So instead of monitoring the battery state manually the Threema Android app should use the intents provided by Android, see [Monitor Significant Changes in Battery Level](https://developer.android.com/training/monitoring-device-state/battery-monitoring.html#MonitorLevel).

When this event is fired, Threema web should show the "low battery" banner.

There should also be an banner showing that the device is in [energy saving mode](https://developer.android.com/reference/android/os/PowerManager.html#ACTION_POWER_SAVE_MODE_CHANGED). This mode can be activated even if the battery is full but i think it may slow down/break the web-app-communication.

**Comment by ovalseven8** [comment]
Well, we have to consider that Threema Web will also be for iOS very soon (hopefully). ;)

> There should also be an banner showing that the device is in energy saving mode.

I don't think that's important
