### ISSUE TITLE
Decrypt chunks as they arrive

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#272]
Right now, incoming chunks are collected and reassembled by the [chunked-dc](https://github.com/saltyrtc/chunked-dc-js) library. Once a message is reassembled, it's being decrypted.

Since nacl uses a block cipher, we can decrypt every chunk as it arrives. That probably saves some time and speeds up data transfer (especially for large files), since decryption happens already while waiting for new chunks to arrive.

Depends on https://github.com/saltyrtc/chunked-dc-js/pull/19

**Comment by lgrahl** [comment]
Need to correct myself, Salsa20 is actually a stream cipher which is theoretically even better for this use case. However, https://crypto.stackexchange.com/questions/6008/streaming-api-to-authenticated-encryption - it's much harder than I thought.

> As pointed in the question, a conservative API to authenticated encryption should only ever release authenticated plaintext on the deciphering side. Anything else is too open to attacks (padding, timing, denial of service, unamit).

So, the first problem is that it doesn't look like the API is capable of doing that because the MAC is being checked at every chunk which obviously fails. Even if we manage to overcome this, will me make us vulnerable towards timing 'n stuff? I mean, we just decrypt the chunks to efficiently use the CPU time between messages - we're not handing them out or anything like that.

**Comment by dbrgn** [comment]
You are right. What we could do is to encrypt each chunk separately (including authentication header), but at 16 KiB chunk size the overhead is probably too large.

**Comment by lgrahl** [comment]
That's 16 bytes which really is nothing in 16 KiB (0.00097%). And the 16 KiB limit is going to die soon. :+1: If you hint me the locations where a file transfer is initiated, I could possibly do a quick proof-of-concept depending on how hard it is to hack this in. :)

**Comment by dbrgn** [comment]
Yeah, that's true. The code is [here](https://github.com/saltyrtc/saltyrtc-task-webrtc-js/blob/master/src/datachannel.ts).

**Comment by lgrahl** [comment]
Had the same idea and started some work in the SaltyRTC demo (sending files and throughput testing). But UI stuff is slowing me down. :unamused:

**Comment by lgrahl** [comment]
@dbrgn I'm starting to wonder if we should switch over to *chunk-then-encrypt* instead of the current *encrypt-then-chunk* approach. I believe *chunk-then-encrypt* will bring quite a substantial improvement to large data upload/download. But it of course means we need a major version increase in the SaltyRTC WebRTC task. And it means we need to keep the chunking protocol in forever... And choose a sane maximum chunk size that minimises overhead and buffer bloat. But I'm fine with all of this if it improves performance in general.

It'd be really cool if we had a performance & throughput app for that purpose. I don't think this should be in the SaltyRTC demo as the code in the demo should remain simple.

**Comment by dbrgn** [comment]
Do we have actual numbers on how long the decryption actually takes? When I last tested it with `nacl-fast.min.js` decryption was really fast.

**Comment by lgrahl** [comment]
But then we tested that on your rather potent desktop. Now, considering how long it takes before I'm even receiving the first chunks (at least several seconds) from my phone (Moto G) when I request a file with a few MiB, it could be the encryption time or something else related to getting the data.

However, I agree that this needs to be tested thoroughly beforehand.

**Comment by lgrahl** [comment]
Will be resolved by chunk-then-encrypt on the road to #498
