### ISSUE TITLE
Bad UI when sending files

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#29]
I sent a video (mp4) to a contact and the UI is really bad here:
![screenshot](https://i.imgur.com/Mykuddq.png)
Yeah, that's the video. :laughing:

I think some improvements are definitely needed here.

Moreover, when I send a file/video/etc. I can check the box "Send as a file". What does this mean?

**Comment by dbrgn** [comment]
> I think some improvements are definitely needed here.

You are right, this is actually a regression that slipped through before the release.

> Moreover, when I send a file/video/etc. I can check the box "Send as a file". What does this mean?

When sending an image, it is by default sent as image message, meaning that the recipient can see the preview, that the image is compressed by the app (if enabled) and that EXIF data is stripped in order to prevent privacy leaks like GPS coordinates in the metadata.

By checking the "send as file", Threema sends the data as a file message instead and does not touch the contents at all. This is useful for example when sending screenshots that should not be compressed, or to retain all EXIF data.
