### ISSUE TITLE
Update Firefox icon when Firefox 57 is released

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#301]
In the app, I mean. The Firefox 57 release [is planned for](https://wiki.mozilla.org/RapidRelease/Calendar) 2017-11-14.

![firefox icons](https://www.soeren-hentzschel.at/wp-content/uploads/2017/08/firefox-logos-2017.png)

Ref: https://www.soeren-hentzschel.at/firefox/neues-logo-firefox-und-firefox-klar/ (German)

**Comment by betamod** [comment]
I think the new logo is an improvement. However, I think that the gradients for Firefox 57 release could be a bit smoother. I like that it has a bit of violet in it but its not blended enough into the lighter colors in the tail. The Firefox Nightly icon does a better job of this. 

Also, I think the contour of the upper arm of the fox should be rounded so that it echos the other circular curves in the logo.

**Comment by rugk** [comment]
Ehm… well… this is nice, but you might better direct this feedback to Mozilla. (don't know if they'll still change the icon, however)

**Comment by ovalseven8** [comment]
Firefox 57 will be released today.

**Comment by Rehan-Arqam** [comment]
Check out this Microsoft New Logo Design Concept!
MSUAAL : Microsoft Universal Amoebic Animated Logo.
Microorganism Amoeba and Microsoft have close resemblance.
Soft-bodied organism Micro-organism : Micro-soft
Ectoplasm & Endoplasm (Founders: Bill Gates, Paul Allen)
Nucleus (Windows)
Food Vacuole (BING)
Contractile Vacuole (XBOX ; As it relieves stress and releases tension)
Pseudopodium's Action (The acquisition of Nokia & other ventures),
etc.

![msuaal](https://user-images.githubusercontent.com/33787927/32982756-31c4b0de-ccab-11e7-83da-c1d7a2dc5b28.jpg)

**Comment by rugk** [comment]
Done in v3.3
