### ISSUE TITLE
"increase power consumption"?

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#35]
In the app and on https://threema.ch/en/threema-web e.g. you state:
> Threema Web might increase power consumption while it is active. You can enable or disable it at any time.

When I am actively using the web client this is obvious, but does it also apply when I no web client is connected?
So when I have "web client" enabled in the options and some may be shown in the list (as they are persistent sessions I've saved with the password), but none of them is actually connected (all red), the Threema app should not use more power than if I toggle the switch off… Is this right?

Otherwise disabling the web client in the app would be cumbersome and it would render the beneifit of the persistent sessions, where you just enter a password an a GCM push wakes up the Threema app, useless. (as you'd have to activate the web client in the app anyway)

**Comment by dbrgn** [comment]
Yes, you're right. If no session is active, the energy consumption level should not increase.

The increase in battery usage is mainly because we need to acquire a wakelock, which prevents the phone from going into deep sleep (which would cause our network connection to terminate). It's only necessary while the connection is actually open though.

**Comment by rugk** [comment]
Label with "question"?
