### ISSUE TITLE
It should be workaround for non-camera smartphones

### ISSUE THREAD

**Issue by murqach** [threema-ch/threema-web#452]
I can't use camera on my smartphone -> can't use threema web :(

**Comment by dbrgn** [comment]
Unfortunately the workaround would be to type 164 symbols into your smartphone... Not really user friendly.

https://github.com/threema-ch/threema-web/blob/master/docs/qr_code.md

Optical transfer of this information is probably the best way.

I'll close this for now, if someone knows of an easy way to transfer this sensitive information to the user that does not require the camera, feel free to leave a comment.

**Comment by lgrahl** [comment]
Via speaker and microphone - @burkeb has experience in this. :grin:

**Comment by murqach** [comment]
What if I have 164 characters code on my device already? Can I type it somewhere in app?

**Comment by lgrahl** [comment]
No. But to be honest I believe it's a useful addition since I'm fairly confident it's easy to add and people's cameras do break...

I think it's possible to fake camera input on Android. [This app](https://play.google.com/store/apps/details?id=com.blogspot.newapphorizons.fakecamera&hl=en) claims it can do the job. Note: I'm not recommending that app and I haven't tested it. It just popped up during a quick search.

**Comment by dbrgn** [comment]
> What if I have 164 characters code on my device already?

The question is how you securely transfer the data to your device. If an attacker could intercept and modify the data, you would transmit all your chats and conversations to the attacker's computer.

> Can I type(paste) it somewhere in app?

Not currently, no.

Fake camera apps might work as workaround.

**Comment by murqach** [comment]
1) short url under qr code (if attacker can modify url he can also modify qr-code)
2) user types url in web browser on device (if attacker has access to device and can modify typed url he has access to threema app too)
3) browser redirects to threema deeplink with full 164 chars info (if attacker can modify https/hsts traffic see 1)

**Comment by dbrgn** [comment]
In that case you would entrust the access to your device to Threema GmbH, since the keys would need to be uploaded to our servers for the short URL to be properly expanded. That would be a departure from the current model where keys never leave the end user devices.

**Comment by BurkeB** [comment]
@lgrahl yoctolicious idea 👍 Just in time for the submission deadline of the [sigbovik conference](http://sigbovik.org/2018/)

Using Microphone/Speaker as a fallback would be really nice. 
Instead of holding your Phone in front of the screen and looking like a weirdo, just put it on the desk, let it listen to a melody for 5 seconds and acoustic data transmission will do the magic.

**Comment by chrisamow** [comment]
This would be helpful for people who can figure out how to get the data there (e.g. magic-wormhole)
