### ISSUE TITLE
What if I like to use Threema and Threema Web completely anonymously?

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#479]
While Threema can be used with pseudonyms only (the Threema ID is basically nothing else), some people would probably like to use Threema completely anonymously using some proxies like Tor. To be able to use it really anonymously we have to make sure that ALL the traffic between the Threema app and servers as well as between the app  and the web client is going through the Tor network and no (real) IP addresses are leaked.

However, Threema uses WebRTC for both the web client and audio calls. Recently, there has been a discussion once again about WebRTC and the continous IP leaks (https://news.ycombinator.com/item?id=16699859).

I am not that familiar with WebRTC itself, so I'd like to ask the expert in that field here (@lgrahl):
What is the current state about IP leaks with Threema and if there're some problems, shouldn't Threema warn people about that?

**Comment by lgrahl** [comment]
Disclaimer: I've never used TOR on Android so far.

### Threema Web

If you use TOR on both sides (TOR browser and app), then Threema Web isn't going to work at all because the TOR browser doesn't allow for WebRTC.

What will work is the SaltyRTC handshake and that will take place over TOR. So, even if you have found a way to use WebRTC in a TOR environment, the signalling data (which contains the IPs) is E2EE and routed via TOR. Since you are the owner of both devices running that, nothing leaks to third parties even though the devices may connect to each other directly.

### Threema Call

If you enable the *Always relay calls* option, TURN should not circumvent the proxy. SOCKS proxies isn't something I'm very familiar with, so I would need to look that up. @dbrgn have you tested that scenario?

---

WebRTC leaking IPs is still an ongoing discussion.
* [Content Security Policy discussion](https://github.com/w3c/webappsec-csp/pull/287) (current *rough* consensus: on/off switch for WebRTC)
* [The discussion about *consent*](https://mailarchive.ietf.org/arch/search/?email_list=rtcweb&gbt=1&index=50nBI9SAUDb3M85GBkY46zvO6rw) e.g. in reality whether capture permissions implicitly give the browser permission to leak IP addresses
* [An experiment by Youenn Fablet from the Webkit devs using mDNS to prevent IP leaks](https://bugs.webkit.org/show_bug.cgi?id=174500#c6)

If you are not happy with the current state, **please take part in the discussion**. The problem and the urgency needs to be made aware to the people who specify this. And that is not going to work if people who are upset raise their anger only in their own little bubble on Hacker News.

**Comment by dbrgn** [comment]
I haven't tested what happens if you use a proxy, but in any case, as @lgrahl said, the signaling connection will use Tor and all ICE candidates (which contain network information) are sent through an E2E encrypted channel between your two devices, so the signaling server is never able to determine what they contain.

I'm not sure what the situation with STUN/TURN is like though. I think it should work fine in Chrome, but Firefox has some quirks / bugs with regard to proxies + STUN/TURN. For example this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1385030 I'd consider these things clear browser bugs.

A possible workaround for this issue would be to make WebRTC optional. That would result in more activity metadata but less (potential, depending on browser) network info metadata.

**Comment by lgrahl** [comment]
Can we close this one?
