### ISSUE TITLE
Make Threema Web a real desktop client

### ISSUE THREAD

**Issue by piegamesde** [threema-ch/threema-web#515]
Threema Web is not a real desktop client, it is no more than a web frontend for the app. As someone who almost exclusively uses the laptop for all communication, this is a real pain. All chat applications nowadays have web clients that are completely independent of the phone (except WhatsApp of course), and Threema should have it too.

## Expected Behavior

I can use Threema on my Desktop / in my browser independently of my phone. I don't have the phone to be online. I am not required to enter a password or scan a QR code on every connection attempt.

## Current Behavior

Threema web is no more than a web frontend for the app. Every thing I do goes through the phone. This is a _huge_ battery drain. Also, every time the connection is lost I need to reconnect it. Sometimes, I don't notice the connection is lost and miss potentially important messages.

## Possible Solution

Threema accounts are not tied to a phone number, but to the Threema ID. So there is no real reason why I should be forced to use mobile devices for using it. I don't care if Threema web has to be my only client, or if there is no sync between them.

## Your Environment

* Threema Web version: 1.8.2
* Threema App version: 3.42.2000418
* Browser name and version: Chromium: 59.0.3071.115
* Computer operating system and version: Arch Linux
* Smartphone operating system and version: Android 4.4.2

**Comment by dbrgn** [comment]
Hi, thanks for your feedback.

The fact that Threema Web connects to your phone is by design. It makes sure that the private key never leaves your phone. It's an extension of your phone, not a standalone client.

From what I understand, what you want is not necessarily multi-client functionality, but a standalone Threema client on your computer so that you don't need your phone at all, right? In that case, maybe https://www.openmittsu.de/ could work for you?

**Comment by ovalseven8** [comment]
I think this is an interesting topic and I basically agree with Threema's decision here.

Most people do instant messaging with the smartphone, now when it comes to using the same ID from multiple devices, it's the best sulution when everything goes through the phone from a security point of view. No duplicated message history, no shared or additional private keys etc. That's a huge advantage when it comes to security because this model is easy to understand and the user can be sure that all the stuff is stored on the phone only.

So, I think it's okay to have a web client for the app on the smartphone. My point here is that the web application should be way more stable, efficient and use less battery. That's not the case at the moment and should be fixed as soon as possible. Even if that means a rewrite with other frameworks or technologies. If the web client is working fine then, it's really a good solution for a private messenger.

However, when you want to use Threema at the desktop only (it's not about multi-device support), I am with @piegamesde and I'd like to have an officially supported Threema client. One of Threema's strengths is that the account is not dependent on mobile phone numbers. However, Threema does not make advantage of that fact at the moment. Let's see if that changes.

**Comment by dbrgn** [comment]
Closing for now. Feel free to leave further comments.

**Comment by jeengbe** [comment]
You can emulate a standalone app with Google Chrome.
You can pass a site to launch in borderless mode (Tabs are disabled)
`~Google\Chrome\Application\chrome_proxy.exe --profile-directory=Default --app=https://web.threema.ch/`

You can also change the icon from the default Chrome Icon to Threema's, which you can find by having a look at the source code
SIcon: `%USERPROFILE%\Pictures\Threema.ico`

You can then use Threema Web like any other application
![image](https://user-images.githubusercontent.com/51749023/88478001-f9915b00-cf44-11ea-8349-4f2d04c84e0a.png)

**Comment by lgrahl** [comment]
If you just want Threema Web in its own separate window - Threema Web is a PWA now, see #407.

**Comment by piegamesde** [comment]
This issue is not about a "native" desktop client, it is about a standalone desktop client independent from the phone. Today, I'd maybe call this "multi device support". Nonetheless, the issue description is pretty clear about what I want(ed), so please don't derail it with related issues.

I personally don't care about this any more, since I've long moved on to other chat applications (Matrix at the moment, FWIW). But others may still do.

**Comment by lgrahl** [comment]
My response was towards @jeengbe.

**Comment by BlkPingu** [comment]
I second this. I only use Threema sparingly because it's not multi-device supported. Please push this

**Comment by lgrahl** [comment]
We've [publicly announced](https://threema.ch/en/blog/posts/open-source-and-new-partner) that we're working on multi-device and a desktop client. No need to push. :slightly_smiling_face:

**Comment by ilu33** [comment]
I don't care about Threema on phones, so I don't need multi-device-support. Was there any progress with a desktop-only client? Is there an ETA?
Thanks for the OpenMittsu mention, I'll have a look. The last commit was almost a year ago though, is it still recommended?

**Comment by langhard** [comment]
Interim solution until an official desktop app is released: Threema's progressive web app can be packaged with Electron with little effort. A tutorial or the ready to download app is available on my (german) blog: https://langhard.ch/download-threema-desktop-client-app/

**Comment by lgrahl** [comment]
One has to be aware that it comes with all the pros and cons of an Electron app. For Threema Web (but not for Threema Desktop), we believe the cons (e.g. potential privilege escalation, potential security vulnerabilities without an auto-update function) outweigh the pros at the moment.

**Comment by BlkPingu** [comment]
> We've [publicly announced](https://threema.ch/en/blog/posts/open-source-and-new-partner) that we're working on multi-device and a desktop client. No need to push. 🙂

Sounds good, as long as this means I don't need a browser on desktop to use Threema when this is released. I'm fine with using a phone to authorise a desktop client to tap into my account, but I want to be able use Threema without opening a browser at all.

**Comment by jeengbe** [comment]
> I want to be able use Threema without opening a browser at all.

That's what PWAs are for :)

**Comment by vulpes9** [comment]
> 
> 
> We've [publicly announced](https://threema.ch/en/blog/posts/open-source-and-new-partner) that we're working on multi-device and a desktop client. No need to push. 🙂

https://threema.ch/en/blog/posts/md-architectural-overview-intro
https://threema.ch/en/blog/posts/md-architectural-overview#main

It's been 6 months since the last update on the blog. I have full trust in your competence and will to make it happen.  
However, can we have a tiny update or life-sign?

**Comment by lgrahl** [comment]
Be assured that we're working on it (quite hard).

**Comment by vulpes9** [comment]
Thank you lots, will buy several more copies of Threema for my friends on the same day it happens.  
Especially for those on Linux who love privacy being free as in freedom 😄

**Comment by vulpes9** [comment]
> Update 30.12.2021: The development of Threema 2.0 for desktop is coming along great, but there’s still a lot to do. We’re currently busy combining frontend and backend. A sneak peek of the new UI can be found [on Twitter](https://twitter.com/ThreemaApp/status/1476490273119252480).
https://twitter.com/ThreemaApp/status/1476490273119252480

So, is this forgotten?

**Comment by Wh1teT1ger55** [comment]
Come on Threema. Publish it

**Comment by threema-lenny** [comment]
The development of Desktop 2.0 is ongoing and a preview is available for iOS: https://threema.ch/en/download-md
If you're curious regarding the development, please see the changelog at the bottom of that page for details.

Please refrain from continuously pinging here. When there's something to announce (e.g. a release, support for Android, etc.), it will be done on the usual channels.
