### ISSUE TITLE
SVG send as black file

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#553]
## Expected Behavior

Send SVGs as they are shown in the preview.

## Current Behavior

Preview works, but when sent, it actually is just a black image.

## Steps to Reproduce (for bugs)

1. Go to https://de.wikipedia.org/wiki/Datei:Threema.svg
2. Right click -> Copy as image
3. Paste in chat.
4. Send.

## Your Environment

* Threema Web version: Version 2.0.0-gh Grosser Mythen
* Threema App version: beta
* Browser name and version: Firefox 61
* Computer operating system and version: Fedora 28
* Smartphone operating system and version: LineageOS 14.1

**Comment by dbrgn** [comment]
SVG files are not modified in any way before sending, they are simply sent as files. By right clicking you are copying the PNG preview (which contains PNG transparency), so this issue doesn't have anything to do with SVG files.

This is not something we can change in Threema Web, since the Threema Protocol sends all images in JPEG format, which doesn't support transparency. When removing the PNG alpha channel, the transparent regions become black.

What we could do is replacing the transparent regions with white. I'll create an internal issue for that. However, if you want to send the image unmodified as PNG, send it as a file.

**Comment by rugk** [comment]
Okay, but then there is still a problem:
* The preview before sending the image in Threema Web and the actually sent image, differ. As such, one cannot even notice the issue before sending the image.

**Comment by dbrgn** [comment]
> I'll create an internal issue for that.

The issue will be fixed in the next Android app release.

**Comment by rugk** [comment]
So they will be white? Hmm... don't know if that is really better than just a black background.

**Comment by dbrgn** [comment]
> So they will be white? Hmm... don't know if that is really better than just a black background.

Your bug report was about this logo: https://de.wikipedia.org/wiki/Datei:Threema.svg

On most screens, transparency will be rendered as white or another bright color / pattern.

If you simply remove the transparency, then the PNG alpha channel becomes black. That results in a black logo on black background. How is that better than a black logo on white background?

**Comment by rugk** [comment]
Well… if you now use a white logo it will also not be visible.
At least it should be consistent with the preview now, so it's okay.

**Comment by dbrgn** [comment]
> Well… if you now use a white logo it will also not be visible.

Yes, but then practically on every preview (including Wikipedia) it will not be visible either.
