### ISSUE TITLE
Allow sending large files

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#7]
Currently file size is limited to 15 MiB because of an issue with WebRTC DataChannel buffering:

https://github.com/saltyrtc/saltyrtc-task-webrtc-js/issues/9

**Comment by ovalseven8** [comment]
Is there any ETA? When I like to send a video that's usually not possible because of this 15 MiB limit.

**Comment by dbrgn** [comment]
I'm also annoyed by this every once in a while, so it's definitely on our list of planned things to do :)

**Comment by lgrahl** [comment]
This is really annoying to fix as well as the data channel API is just so clunky. We have a low water mark event which will tell us when to unpause sending but there's no high water mark event which tells us when to pause sending. The spec says that `send` should throw an `OperationError` in case no buffer space is available. But as far as I can recall, Chrome just closes the data channel and Firefox endlessly buffers your data until you're OOM (which isn't optimal either because of backpressure but it's fine for our use case). Other than that, the buffered amount low event only raises if the buffer is completely empty in Chrome-based implementations. This means, sending will slow start again and has other issues which are a throughput killer, see https://github.com/sctplab/usrsctp/issues/142.

**Comment by lgrahl** [comment]
High on my to do list. :stuck_out_tongue_closed_eyes:
