### ISSUE TITLE
Content Security

### ISSUE THREAD

**Issue by SkateScout** [threema-ch/threema-web#702]
Hi,

since this an application that is about privacy there should be also payed attention in the web client.
a) No external Linking for example there is an try to load an resource from "https://errors.angularjs.org/"
b) With CSP (Content-Security-Policy) in mind and to avoid xss or script injection please avoid the usage
   of 'unsafe-inline' 'unsafe-eval'.
   Because without this two dangerous options the web client is not usable.

**Comment by dbrgn** [comment]
>  a) No external Linking for example there is an try to load an resource from "https://errors.angularjs.org/"

This is definitely not intentional, we try to avoid all and any external resources.

I cannot find a case where a resource is loaded from `errors.angular.js.org`. I only found related code in `angular.js:102` where a URL is constructed for error reporting (in the browser console). Can you point me to a place where an external resource is requested?

Furthermore, we don't allow connections for foreign domains in our CSP policy, so the request would fail anyways (unless we made a mistake in the CSP).

>  b) With CSP (Content-Security-Policy) in mind and to avoid xss or script injection please avoid the usage of 'unsafe-inline' 'unsafe-eval'.

Unfortunately when we last checked (in 2016) it was not yet possible to integrate AngularJS with a stricter eval/inline policy. This may have changed, I will revisit this issue next week to check if there's a way to disable those two options.

**Comment by SkateScout** [comment]
I found the url because my browser reported it as an CSP violation. It is possible that it was an error report. But in depended of error or not there should be no data transmission to an third party. I think this is one
of the reason some people like the self hosted version. Maybe it would be an good idea to enable csp-report on your csp rules to so that you can see such violations ?

**Comment by rugk** [comment]
@SkateScout It could also be an error caused by one of your installed add-ons. Try testing it with all add-ons (temporarily) disabled. Also browser (version) would be helpful. (AFAIK Firefox does not apply the CSP to add-ons anymore, since some versions, so this annoying errors should not appear.)

**Comment by dbrgn** [comment]
@SkateScout again, are you sure that a request was made to errors.angularjs.org?

When an error occurs, AngularJS will construct an error message like this one:

![img](http://i.stack.imgur.com/xDUDY.jpg)

As you can see, it contains a URL to errors.angularjs.org. But that is not an error reporting or logging site, it's a documentation page that explains the error and how to solve it.

Neither do I see code in the function that generates this URL which would request the URL. We do *not* collect any analytics data or automated error reports from Threema Web users.

**Comment by dbrgn** [comment]
Ok, back to your original report:

>  a) No external Linking for example there is an try to load an resource from "https://errors.angularjs.org/"

I manually provoked an AngularJS exception in the source code. This is how it looks like in the console:

![img](https://tmp.dbrgn.ch/screenshots/20190107165026-we0h7wl9.png)

The network monitor did not report any requests outside of our own domains. If you insist that this happened, please show some evidence :slightly_smiling_face: 

Regarding stricter CSP rules, I have opened #707.
