### ISSUE TITLE
Interoperability with xmpp

### ISSUE THREAD

**Issue by tursiops33** [threema-ch/threema-web#766]
Dear everyone, 
I recently discovered this project and after going through the faq I couldn't find any answers to this:
Can threema be used with xmpp? If not would it be possible to create a bridge?
I run an xmpp server that I use myself and would love to be able to chat and use the app with my xmpp account so as not to have to create another one and have to bring my friends to a new platform. 

Thank you in advance

**Comment by dbrgn** [comment]
Hi. This is the wrong issue tracker since the question affects the apps and not the webclient :slightly_smiling_face: 

> Can threema be used with xmpp?

No, that's not possible. The protocols are fundamentally different.

> If not would it be possible to create a bridge?

Theoretically yes (see https://gateway.threema.ch/), although the bridge would need to terminate the end-to-end encryption and could read all contents. (Bridges and end-to-end encryption don't play well together across protocols...)

Right now the Gateway offer is not really aimed at integrations like that though, you have to pay for every message (it's more like an SMS gateway used for text messages, broadcasts, alerting, etc). The Threema Gateway product model might change in the future, but right now it's not really feasible to build a full XMPP integration, as you would probably need a separate Threema Gateway ID for every XMPP contact.

(Note: If you mainly want a standalone Threema client that runs on the desktop, check out https://www.openmittsu.de/. You won't be able to share the ID between your mobile and the desktop though.)

**Comment by alexanderadam** [comment]
> > Can threema be used with xmpp?
> 
> No, that's not possible. The protocols are fundamentally different.

It seems that @genofire is working on a XMPP/Jabber transport since about a year:

https://dev.sum7.eu/sum7/thrempp

I don't know whether it is usable, though.

**Comment by genofire** [comment]
Nope, the current state of thrempp is not usable (it has only supported p2p communitcation).
 ATM, I do not have time to reconstruct the current API of threema.
