### ISSUE TITLE
Setting a large profile picture will not allow a connection to Threema Web

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#768]
## Expected Behavior
Setting a new profile picture in Threema Web should have no side effects except that the profile picture is updated.

## Current Behavior
When setting a new profile picture from a large jpeg the iOS app will not be able to reconnect on the next session. It will get stuck on 99%.

## Possible Solution
Check the size of the profile picture.

## Steps to Reproduce (for bugs)
1. Set a new profile picture that is quite large such as this one in Threema Web: https://unsplash.com/photos/loGTCYD03n0
2. Refresh the page
3. Try to connect to Threema Web again
4. It will get stuck on 99% (at least on my connection, maybe it has something to do with connection speed)

## Your Environment
* Threema Web version: 2.1.7
* Threema App version: 4.1.2, 4.1.1
* Browser name and version: Firefox 65.0.1 and any other browser
* Computer operating system and version: macOS
* Smartphone operating system and version: iOS 12.1.4

**Comment by lgrahl** [comment]
Investigated and found a race condition between `response/receivers` and `response/profile` where the former depends on the latter being processed. Due to the size of the profile picture, the `response/receivers` has been received before `response/profile`. Will be fixed in the next release.

However, there are two more issues:

1. The picture should have been resized to 512x512 by the web client, filed #770.
2. The app should resize the image regardless of whether the web client already did. This obviously requires an app update.

**Comment by joelfischerr** [comment]
I have not looked into it very thoroughly but the large profile picture seemed to have also caused the iOS app to become slow and reload many profile/group pictures each time the chat list is loaded. Setting a new picture to all groups I have created through Threema Web has increased responsiveness of the iOS app.
It might be worth it to resize all existing profile/group pictures or at least to keep it in mind for the support team.
