### ISSUE TITLE
Show notification settings

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#8]
Make it possible to enable/disable desktop notifications.

**Comment by IndianaDschones** [comment]
I have implemented this feature.
But I will wait untill the pull request #110 is merged into master in order to integrate the notification settings into the settings and to store the preference in loacal storage.

**Comment by FloThinksPi** [comment]
nice to see someone already building that :) , i think until the pull request can get fully accepted into master this will still take some time because of the Theming thing.  I could try to get the changes for the settings menu into a separate pull request. @dbrgn Or does it make more sense to make a WIP branch for settings features ?

**Comment by dbrgn** [comment]
@FloThinksPi maybe you could extract the (empty) settings dialog to a separate pull request, if you're well-versed with cherry-picking / rebasing :) We could then merge that to master so that @IndianaDschones can integrate the notification settings.

**Comment by dbrgn** [comment]
@IndianaDschones the (empty) settings dialog and the settings service have now been merged to master!

**Comment by IndianaDschones** [comment]
@dbrgn I think we can merge the notification settings today. I´ll performe some tests and if everything goes well, we´re ready to go 😄

**Comment by dbrgn** [comment]
@IndianaDschones btw, I did some small changes to notifications in #108. Shouldn't affect you though.
