### ISSUE TITLE
New groups from app not show up in Threema Web

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#804]
## Expected Behavior

New groups should always be synced and thus show up in Threema Web.

## Current Behavior

The group does not show up in Threema Web. (even after sending a message in that group)

## Steps to Reproduce (for bugs)

1. Open Threema Web.
2. Create a new group _on the phone_!
3. (optionally) Send a message in that group.

## Your Environment

* Threema Web version: 2.1.7-gh
* Threema App version: 3.7
* Browser name and version: Firefox
* Computer operating system and version: Linux/Fedora 30
* Smartphone operating system and version: Android 7

**Comment by dbrgn** [comment]
Confirmed, this seems to be an Android app bug. Thanks for bringing this up.

**Comment by dbrgn** [comment]
I have to correct myself. The group was correctly created both on the phone and in Threema Web. (I just didn't notice it at first because without writing a message the empty group was sorted all the way at the bottom of the conversation list. After writing a message, it moved to the top.)

@rugk can you still reproduce the issue?

**Comment by rugk** [comment]
Works.
