### ISSUE TITLE
App Crashes on connecting to Web session

### ISSUE THREAD

**Issue by Simon-Schulten** [threema-ch/threema-web#814]
## Bug Description

iOS app crashes when connecting to web client. Then loading of web client is restarted, but succeeds to the usual interface, albeit with empty conversations. It is possible, however, to select a contact and then this conversation loads properly.

## Steps to Reproduce (for bugs)

1. Open Threema on iOS
2. Open Threema Web Client
3. Either start a new connection or reconnect with password.

## Potential Solution

No clue, I'm not a developer. Just a dull economist.
Sorry if this should be a duplicate. I did have a look, but nothing came to my attention.

## Your Environment

* Threema Web version: Version 2.1.7 Glärnisch
* Threema App version: iOS Version 4.2.3
* Browser name and version: Firefox 67, Chrome 75.0.3770.80 
* Computer operating system and version: Ubuntu 18.04.2 LTS
* Smartphone operating system and version: iOS 12.2

**Comment by dbrgn** [comment]
Thanks for the report! Sounds like a bug in the app to me.

Since this concerns the iOS app, it's best to contact `*SUPPORT` through Threema and to send along a validation log that was recorded during such an app crash (Settings > Advanced, then enable validation logging). In that case your request will be passed on to the iOS developers.
