### ISSUE TITLE
Update TLS configuration for Threema Web

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#842]
I highly recommend the new [IT Security Guidelines for Transport Layer Security (TLS)](https://english.ncsc.nl/binaries/ncsc-en/documents/publications/2019/juni/01/it-security-guidelines-for-transport-layer-security-tls/IT-Security-Guidelines-for-Transport-Layer-Security.pdf) by the [National Cyber Security Centre](https://english.ncsc.nl/).

Because Threema Web relies on modern browsers, you should use the **Good** options only. The browser vendors [will remove TLS 1.0/1.1 support](https://hacks.mozilla.org/2019/05/tls-1-0-and-1-1-removal-update/) in March 2020. So I guess that would be a good time to update the TLS configuration.

Since your current config is sane, just consider this as a friendly reminder. :smiley:

**Comment by rugk** [comment]
THe biggest issue I see is that TLS 1.3 is not yet supported on their servers. Which is unfortunate.

And instead of pages long PDFs, I'd suggest https://ssl-config.mozilla.org/, but they have the same advice. :smiley: Actually, their modern config _only_ supports TLS 1.3, which is quite drastic IMHO…

**Comment by lgrahl** [comment]
I can see why you opened the issue here but technically it's not related to the project.

I'd suggest sending this to `*SUPPORT`.
