### ISSUE TITLE
Threema app shows "Manual start required"

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#853]
## Bug Description

With Threema v4-beta3 there is this "Manual start required" now for my two Threema Web sessions. I already noticed in the past that sometimes the sessions do not work anymore. However, I do not understand WHEN AND WHY that occurs.

I believe that's the new (and better!) design instead of the red exclamation mark icon?

Can someone clarify the situation?

![Screenshot_20190715-144538](https://user-images.githubusercontent.com/8258609/61217133-5a217180-a70f-11e9-93f4-810a8c7c7f41.png)

**Comment by ovalseven8** [comment]
@dbrgn: Note that this is not necessarily a bug but a question. I do not understand when/why "Manuel start required" occurs sometimes and if that's intentional.

**Comment by lgrahl** [comment]
If you have push services enabled, it's a bug.

**Comment by ovalseven8** [comment]
Okay, then it's a bug :D

**Comment by lgrahl** [comment]
If this only occurs in the app, report a log to `*SUPPORT`. Reopen if it also occurs in Threema Web. :slightly_smiling_face:

**Comment by ovalseven8** [comment]
Well, I can't provide any useful logs etc.

This happens only sometimes. E.g. when a reconnection attempt is not successful it looks like somehow the session is set to "Manual start required"

**Comment by lgrahl** [comment]
I don't see the problem to leave the log enabled and report it when it happens. :slightly_smiling_face: But @dbrgn may also want to look into it.

**Comment by dbrgn** [comment]
Clarification: "Manual start required" is shown if the push token in your Android app has changed since the last time you used this Threema Web session.

This means that the session stored in your browser can try to wake up your app (by sending pushes) all day long, it won't work because the old push token is not valid anymore.

Therefore you need to manually start the session once. During the connection buildup, the new push token is sent to the browser and session restoring will work again.

**Comment by dbrgn** [comment]
(Addendum: Usually your push token doesn't change. I've never seen that message in real life so far. If your push token changes frequently, then something funny is going on with your Google Play Services.)
