### ISSUE TITLE
Pasting text with '<' and '>' doesn't work correctly

### ISSUE THREAD

**Issue by simmac** [threema-ch/threema-web#86]
## Expected Behavior

When pasting text like 
`lorem ipsum x<y blah blah` or `lorem ipsum x<y blah blah y>z foo bar` into the message text field, exactly this text should appear in the text field.

## Current Behavior

The first text gets cut off at the '<' character, only `lorem ipsum x` appears in the text field.
In the second sample, everything between the two brackets disappears, resulting in `lorem ipsum xz foo bar`.

## Possible Solution

There is probably something up with [the regexes in filter.ts](https://github.com/threema-ch/threema-web/blob/master/src/filters.ts#L64-L65), I couldn't find anything obvious, though.

## Steps to Reproduce (for bugs)

1. Copy `lorem ipsum x<y blah blah y>z foo bar` into your clipboard
2. Paste into the message text field
3. Compare the text in the text field with the text in your clipboard

## Your Environment

* Threema Web version: 1.0.2
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Chrome 56
* Operating system and version: macOS 10.12

**Comment by dbrgn** [comment]
Thanks for the report! The source of the problem is probably here:

https://github.com/threema-ch/threema-web/blob/master/src/directives/compose_area.ts#L355-L356

AngularJS sanitizes HTML tags using a whitelist.

Instead of sanitizing the input, we should probably switch to escaping of "dangerous" symbols like `<` (with the exception of images, since pasting emoji should work). Tricky to get right in all cases :)
