### ISSUE TITLE
Error: Could not bootstrap application ReferenceError: 'TextDecoder' is not defined

### ISSUE THREAD

**Issue by cluick** [threema-ch/threema-web#891]
When I open https://web.threema.ch in the Microsoft Edge Browser (Version 44.18362.1.0; Windows 10 Pro 1903 Build 18362.239) only the background image is visible and the dev tools console shows the following output:

```
CSP14309: Unbekannte Direktive block-all-mixed-content in Content-Security-Policy. Die Direktive wird ignoriert.
Compat: WebAssembly is supported
Could not bootstrap application ReferenceError: 'TextDecoder' is not defined
```

Can I provide any other information that would help you to fix this issue?

Thank you and best regards,
Christof Luick

**Comment by lgrahl** [comment]
Edge is not officially supported since it will not work with Android devices due to the lack of `RTCDataChannel` support in Edge. We could probably let Webpack polyfill `TextDecoder`/`TextEncoder` but I want to hear @dbrgn's opinion. In any case, we'd at least have to detect this.

@dbrgn: Side note: We can revert [this](https://github.com/threema-ch/threema-web/blob/master/webpack.common.js#L8) now since we detect Firefox 52 ESR by checking for WebAssembly support.

**Comment by dbrgn** [comment]
Sounds good to me. I'll prepare a PR.

> @dbrgn: Side note: We can revert this now since we detect Firefox 52 ESR by checking for WebAssembly support.

Good point!

**Comment by dbrgn** [comment]
Note: I won't include a polyfill since the current version of Edge (version 76, apparently) should support TextDecoder. @cluick please try updating to the latest version. Note that Threema Web for Android will still not work with the latest Edge, since they lack WebRTC Data Channels (unless they already switched to the Chromium engine). But at least a proper error message should be displayed.
