### ISSUE TITLE
Can't click on a quoted message to jump to the original one

### ISSUE THREAD

**Issue by chriba** [threema-ch/threema-web#905]
## Bug Description
In Threema Web, you can't click on a quoted message to jump to the original one, as you can do in the app.

## Your Environment
* Threema Web version: 2.2.1

Edit: depending on whether this feature was ever included in Threema Web, this would be either a bug report or a feature request!

**Comment by dbrgn** [comment]
This will be hard to implement, since the "jump to quoted message" feature is currently implemented as text search in the chat database, not using a message ID. That's easy to do in the app which can search all messages in a chat, but since Threema Web only loads the latest n messages, we cannot apply the same technique.

So right now this is unfortunately a lot of work. If the implementation of quotes in the app changes to include the reference message ID, we can reconsider this. Until then, I'll close this feature request, sorry.
