### ISSUE TITLE
error message session closed by protocol error

### ISSUE THREAD

**Issue by jajajack** [threema-ch/threema-web#922]
## Steps to Reproduce (for bugs)

1. send a picture in a chat to a user
2. try to open that chat in threema web after that
3. error message comes up: Protocol error... 
4. cuts connection from webinterface

## Potential Solution

1. Delete the picture on your mobile app, then everything is working again.

## Your Environment

* Threema Web version: threema 2.2.1
* Threema App version:
* Browser name and version: safari 13.0.3
* Computer operating system and version: MAC os Catalina 10.15.1
* Smartphone operating system and version:

**Comment by rugk** [comment]
You left an empty issue template, I guess there is really a little more information needed on whys/how this happens…

**Comment by jajajack** [comment]
sorry! new here.... 
fill it in right away :)

**Comment by jajajack** [comment]
More clear now ? :)

**Comment by lgrahl** [comment]
Which app version are you using?

**Comment by jajajack** [comment]
4.4.1 (2492)

**Comment by dbrgn** [comment]
We mainly had this issues with the app versions before 4.4.0. If you already used v4.4.1 when this problem occurred, then there must be a new bug.

In the iOS app, please navigate to “Threema > Settings > Advanced” and activate "Validation logging".

Then, once the problem occurred again:

- In Threema Web, without reloading the page, click on "Troubleshooting" in the footer and send the logfile to the support (https://threema.id/*SUPPORT)
- In the app, please navigate to "Threema > Settings > Advanced" and tap on "Share Log".

Please also let the support know at what time the problem occurred. This helps diagnosing the problem.

I'll close this issue for now, but will re-open it in case the bug is in Threema Web and not in the app. Thanks for the report!
