### ISSUE TITLE
How does skin tone selector work?

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#945]
## Bug Description

Just wanted to try out the new "skin tone selector" in Threema Web 2.3.0. Honestly, perhaps I am just too stupid to understand how it works (:smile:), but when I click on a skin tone there is absolutely no effect.

Does it work for you all?

## Your Environment

* Threema Web version: 2.3.0
* Threema App version: 4.22 (Android)
* Browser name and version: Firefox 71
* Computer operating system: Linux

**Comment by rugk** [comment]
Yes, maybe you just need to scroll down a bit until the [skin tone "modifiable" emojis](https://emojipedia.org/modifiers/) (basically all that look somewhat like a human and not a yellow ball with eyes :wink:) actually are listed, because at the top there are only the smileys that are always yellow.

**Comment by dbrgn** [comment]
:smile: exactly.

**Comment by ovalseven8** [comment]
Thanks @rugk! :smile: 😬
